### PR TITLE
fix: do not increment reference counting for references made with 'gst_bin_get_by_name'

### PR DESCRIPTION
**Pull request by caioaamaral**

### CODE REVIEW

**Comment by jhonasiv** [comment]
I have no idea what I am looking at. Can you explain the bug?

**Comment by caioaamaral** [comment]
> I have no idea what I am looking at. Can you explain the bug?

basically, we were creating a bunch of invalid references, resulting in them never being actually deleted. The actual effect of that was the program spawning thousands of threads and at some point segfaulting.

apparently, `gst_bin_get_by_name` already creates a reference, so we should not call `gst_object_ref` on it

@doudou probably can explain that better

**Review by jhonasiv — APPROVED** [review]

**Comment by doudou** [comment]
Expanding on @caioaamaral's explanation (which is pretty good if you replace 'references' by 'reference count')

GStreamer (more generally, GLib) uses reference counting extensively. When reading the API's documentation, one has to be very careful as to whether a returned object is already reference counted or not, and who is responsible to de-ref it.

Looking at the backtrace that Caio managed to get, it seemed that we had an issue with resources not being freed (LOTS of threads created by gstreamer's webrtc). I started looking around and verified that gst_bin_get_by_name transfers ownership to the caller, that is the caller has to deref (but not add-extra-ref) it.

In principle, we should be doing this for the whole code. I hate refcounting.

**Review by doudou — APPROVED** [review]

**Comment by caioaamaral** [comment]
CI is good, merging it

**Pull request merged**
